### ISSUE TITLE
PHP 8.1 errors.

### ISSUE THREAD

**Issue by spacedmonkey** [WordPress/create-block-theme#168]
Getting notice errors in PHP 8.1. 

<img width="1523" alt="Screenshot 2022-12-28 at 00 42 52" src="https://user-images.githubusercontent.com/237508/209740490-b6ab846d-8a01-41b8-8031-757eb40f2336.png">

**Comment by markchagers** [comment]
Same issue: lots and lots of errors in the admin pane (with WP debug on). Additionally generated zip files (when cloning a theme) are corrupt, can not be uploaded to the same Wordpress instance they were generated from, nor be opened with other unzip tools.

**Comment by t-hamano** [comment]
The error that always appears on the admin page is because the first argument of `add_submenu_page` is set to `null`.

https://github.com/WordPress/create-block-theme/blob/ba668354df2f733cef0e0c25634f25baceeaf95c/admin/class-manage-fonts.php#L34-L41

This is a technique to prevent the menu from appearing in the list. A similar problem has been reported with [Site Kit by Google](https://github.com/google/site-kit-wp/issues/5110).

This issue has also been reported as a Core ticket, and it seems preferable to resolve it on the plugin side:

- https://core.trac.wordpress.org/ticket/57581
- https://core.trac.wordpress.org/ticket/57580

**Comment by markhowellsmead** [comment]
This issue is still provoking the deprecation notices in all of our installations which use the plugin. WordPress 6.3.1 and PHP 8.1.

**Comment by markhowellsmead** [comment]
These issues are still preventing use of this plugin. Are they not going to be fixed?

**Comment by pbking** [comment]
The team responsible for building this plugin has been working primarily on the WordPress 6.4 release lately.  We will be returning to work on this plugin in the near future so yes they will be fixed.  The project is not dead.  It just hasn't been the highest priority of late.
