### ISSUE TITLE
Could we run the pre-commit linter/prettier just on the modified lines of a commit and not on the entire file?

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/create-block-theme#217]
The idea is to make the PRs that modify large unformatted files readable.

**Comment by mikachan** [comment]
I'm not sure I've seen a linter work like this before, and if we implemented this it would take much longer for the whole project to be linted correctly. There aren't actually that many files that need to be fixed - as soon as they're linted, this won't be a problem. We could probably tackle a couple of files in one PR, such as all the CSS.

But I'm happy to be persuaded otherwise! It looks like there's an ESLint plugin that helps you lint only the changed lines, so that would cover the JS files: https://www.npmjs.com/package/eslint-plugin-diff

**Comment by t-hamano** [comment]
Personally, I think it is better to format all files according to the current rule set. For example, format CSS, JS, PHP and others (yml, json) with their respective PRs. If we can complete the formatting first, we will be able to see only pure diff in PRs.

**Comment by mikachan** [comment]
As a start, I've run the linter on all the CSS files here: https://github.com/WordPress/create-block-theme/pull/235

**Comment by madhusudhand** [comment]
Please hold with the PHP linter until #237 is merged to avoid conflicts.

**Comment by madhusudhand** [comment]
Fixed lint issues with auto fixer here #252

**Comment by madhusudhand** [comment]
All the list issues are fixed in #252, #253, #254, #255
Any new commit will notify the lint issues and they are expected to be fixed before creating the PR.
Closing this issue as it is no longer needed.
