### ISSUE TITLE
Lint issue: Use double spaces instead of Tabs for nesting.

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/create-block-theme#265]
With tab based indentation, code is not readable specially with react code which is nested to many levels.
Use double spaces instead.

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/1935113/223959915-12c00d0a-c590-48c2-b207-84dd167f875b.png">

**Comment by mikachan** [comment]
I'm not sure if we should move away from tabs as this formatting style is part of the WordPress Prettier config: https://github.com/WordPress/gutenberg/blob/a770dfd075933f0cee7fcd00ddb9361d9ef90ddc/packages/prettier-config/lib/index.js#L20

**Comment by vcanales** [comment]
If this is specific to reviews, you can modify how tab size is rendered on your GitHub account settings
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/managing-your-tab-size-rendering-preference# — TL;DR: Scroll down to "Tab size preference" on this page https://github.com/settings/appearance

The .editorconfig file included in the project makes it so that they render at a more readable size in the editor if you have the extension installed; for VS Code, that is [this extension.](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)

**Comment by t-hamano** [comment]
I believe that tab indentation should be used, following [WordPress Coding Standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/). Tab indentation appears to be recommended in all HTML, CSS, JavaScript, and PHP.

**Comment by mikachan** [comment]
I'm going to close this as moving away from tabs does not align with the WordPress Coding Standards. Please re-open if anyone wants to continue the discussion.
