### ISSUE TITLE
Fatal Error on plugin setup (PHP 8.0)

### ISSUE THREAD

**Issue by kishanjasani** [WordPress/create-block-theme#269]
**How to Replicate:**
1. Clone plugin from repo: `git clone git@github.com:WordPress/create-block-theme.git`
2. Run `composer install` and `npm install`
3. If you forget to run `npm run start` or `npm run build`
4. It will throw an error on `Apperance -> Manage Theme Fonts`

**Screenshot:**
https://prnt.sc/50oJvHvkyJaQ

**Comment by matiasbenedetto** [comment]
Hi, @kishanjasani ! :wave: 

I think this is the expected behavior (failing if the javascript app is not built yet).

The need to run `npm run build` is documented here https://github.com/WordPress/create-block-theme/blob/trunk/CONTRIBUTING.md#how-can-i-contribute so I'm closing this issue. Feel free to re-open if you think we should change something around this.
