### ISSUE TITLE
Include print.css

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/create-block-theme#404]
With Wordpress being used by more that 40% of the internets websites, it also has a big responsibility - not only in in the technological environment but also for the environment of our planet.
With this plugin thousands of websites will be created and, let's face it, even in 2023+ printing documents and websites on real paper is still a thing in some industries.

So, what do you think about including a boilerplate print.css, that has at least for some basic and commonly used elements included?

As inspiration here is a namesake project: https://github.com/BafS/Gutenberg

As a final argument: we owe it to Mister Gutenberg that documents are printed resourcefully and beautifully 😉

**Comment by mikachan** [comment]
This makes sense, thanks for opening an issue for it. 

I agree that there should be a print stylesheet included, however, I'm wondering if this sits more with Gutenberg rather than this plugin. It would be great if each block could provide print styles, and they were compiled into a default print stylesheet. This would mean the responsibility wouldn't sit with the theme and would allow for themes to override the default print styles.

> As a final argument: we owe it to Mister Gutenberg that documents are printed resourcefully and beautifully 

I like this argument!

**Comment by hanneslsm** [comment]
> I'm wondering if this sits more with Gutenberg rather than this plugin

Now that the plugin has evolved, I agree. Closing this issue.
