### ISSUE TITLE
Site editor changes are not copied to child/sibling themes

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/create-block-theme#46]
### Problem

Site editor changes are not copied in new themes.

### Steps

* Create a child theme of Blockbase (call it Blockbase Child) and activate.
* Do edit to post and footer in site editor
* Now create a clone or sibling theme and activate it.
* Observe that only few updates copied to new theme.

Update post content styles

<img width="400" src="https://user-images.githubusercontent.com/1935113/156721196-f406764b-9233-4c0c-bae9-7aea5dc0a4bf.png">

Updated style of index/footer
<img width="400" src="https://user-images.githubusercontent.com/1935113/156721075-7455f057-744d-42c2-ac44-e24199791e5c.png">

Now create a clone or sibling theme and activate it.
Observe that only few updates copied to new theme.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/1935113/156721836-d7fbfcf9-729b-462d-8add-e7ae694b2912.png">

Parts is empty and templates has only index.html

<img width="469" alt="image" src="https://user-images.githubusercontent.com/1935113/156721977-41aa1281-f5a3-4abe-aa14-b6d9143c10c9.png">

**Comment by madhusudhand** [comment]
This is issue only when new theme created from a child theme.

Doing edits in a parent theme and creating a child them from it works good.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/1935113/156724013-3599f0b8-2dfd-4310-bd1c-b008861b0a54.png">

**Comment by pbking** [comment]
I have also reproduced this when EXPORTING a child theme.  To see the reproduction you have to remove the user customizations, else you will continue to see the content as you expect (though it is coming from the database as user changes rather than from the theme templates).

<img src="https://user-images.githubusercontent.com/146530/156903658-410d1dd9-4583-4f23-8946-3dcaf9f21c6a.png" width=400>

Seems to be the call to `add_templates_to_zip( $zip, 'current' )` is not working as expected.
