### ISSUE TITLE
Add a theme.json editor

### ISSUE THREAD

**Issue by creativecoder** [WordPress/create-block-theme#491]
I'm seeing that even theme builders who work mainly from the Global styles interface still need to directly edit theme.json files for some settings.

Adding a theme.json editor to Create Block Theme could have multiple benefits:

- Help avoid needing to switch to a text editor to make these changes
- Show theme.json structure and valid settings to speed up workflows and provide built in documentation

A super basic version of this would be enabling the existing theme file editor to access theme.json.

A more advanced version could use the schema of theme.json to show what options are available and valid for the area of the file you are working in, perhaps using autocomplete, or having a more structured interface, like checkboxes for booleans and drop-downs when there is a limited set of valid choices.

**Comment by pbking** [comment]
Consider linking to this editor as a first pass: /wp-admin/theme-editor.php?file=theme.json&theme=twentytwentyfour



![Image](https://github.com/WordPress/create-block-theme/assets/146530/423371df-1741-4efd-b702-810573f951cd)

**Comment by richtabor** [comment]
We don't recommend editing the theme's theme.json file though? I think this can easily create confusion as global style changes are saved for users during an update while a theme's theme.json file will be overwritten.

**Comment by richtabor** [comment]
> A more advanced version could use the schema of theme.json to show what options are available and valid for the area of the file you are working in, perhaps using autocomplete, or having a more structured interface, like checkboxes for booleans and drop-downs when there is a limited set of valid choices.

I lean towards not trying to replicate a solid IDE; it's a lot of work and maintenance—for little benefit.

**Comment by richtabor** [comment]
> I'm seeing that even theme builders who work mainly from the Global styles interface still need to directly edit theme.json files for some settings.

Do we have a working list of these that we can help migrate to UI? Perhaps CBT can add the more nuanced theme.json controls that core may not add. CBT can add those that are more likely to be integrated as well, as initial explorations — much like how the font library progressed. 

This seems like a more rewarding effort.

**Comment by mikachan** [comment]
> Do we have a working list of these that we can help migrate to UI?

We do have them written down but they're not yet triaged. We're planning on publishing a roadmap for the plugin so I think that will help clear up the plans for what goes into CBT or Core.

> We don't recommend editing the theme's theme.json file though? 

I understand that it's not recommended, but from our recent discussions with theme builders, this is a sought-after feature. I think we could ship [the simple version](https://github.com/WordPress/create-block-theme/pull/520) first and then see what the feedback is from there.

**Comment by bacoords** [comment]
> I understand that it's not recommended, but from our recent discussions with theme builders, this is a sought-after feature. I think we could ship https://github.com/WordPress/create-block-theme/pull/520 first and then see what the feedback is from there.

Agreed - there are still SO many design possibilities in theme.json that you can't do in the site editor. 

> I lean towards not trying to replicate a solid IDE; it's a lot of work and maintenance—for little benefit.

There are codemirror extensions ([example](https://github.com/acao/codemirror-json-schema)) for showing JSON schema hints and linting which could be helpful for the initial version without too much overhead / debt. It would pull in basic info about theme.json and help you validate before saving.

--- 

Just noting that it seems that the initial plan here (based on the PR) is to actually edit the current theme's `theme.json` file, similar to how the theme "metadata" panel works. Just pointing this out as I think it'll be an additional education piece that if some users are using CBT to design a child theme, they'll need to generate that child theme _before_ they use some of these tools, especially because they'll need to save to see the changes in the editor.
