### ISSUE TITLE
Create boilerplate theme

### ISSUE THREAD

**Issue by jffng** [WordPress/create-block-theme#68]
Sorry if this question is naive!

What do you think about adding a fifth option to the plugin — create a new boilerplate theme from scratch, maybe based on block-canvas or something like it? 

When I meet folks that are new to block theming, the first thing they always ask is for a reference point — a starter, boilerplate block theme. Also the name of this plugin implies it could create a "new" theme, to me, maybe disconnected from the currently active one. (This is the perspective of someone who has used "create-react-app" before coming to WordPress, and using that utility results in a blank application, granted there's more tooling and overhead involved there because of webpack...) 

This might make more sense as a CLI or maybe even in Gutenberg itself, but wanted to ask in any case.

**Comment by MaggieCabrera** [comment]
I'd love to have this be a part of core. We could start exploring the integration of that within this plugin in the meantime or try directly in the editor, but I think this is a very needed next step.

The main concern I see about having this on core is how good the experience is for users when there's still stuff needed on a theme like alignments CSS, maybe that's reason enough to start exploring here and then trying to push for the functionality to exist on core natively.

**Comment by MaggieCabrera** [comment]
And as to the boilerplate, I'd go as simple as possible. Think about empty theme with very little extra.

**Comment by carolinan** [comment]
For creating a theme without code only using the site editor, I believe a starter theme needs:

templates/index.hml
style.css -only for the style header
theme.json:

- Version
- Appearance tools enabled, otherwise, many options are missing
- Layout -content width and wide width -otherwise the wide and full align does not work.
- Spacing units -otherwise, only px is available (this surprised me, but that's what my testing shows).
- System fonts registered under typography and set as default font under styles -Otherwise, the browser default is used which  is not nice ;)

These settings can't be adjusted in the global styles so the theme needs a theme.json.

**Comment by MaggieCabrera** [comment]
> For creating a theme without code only using the site editor, I believe a starter theme needs:
> 
> templates/index.hml 
> style.css -only for the style header 
> theme.json:
> 
> 
> 
> These settings can't be adjusted in the global styles so the theme needs a theme.json.

+1, I wouldn't add much more than this, else there's no difference between our boilerplate and any other theme if your first step is going to be to remove a lot of stuff that you don't need

**Comment by carolinan** [comment]
I think developers and no-code users have different needs. I can see that a developer might want more of a head start like "underscores"

**Comment by MaggieCabrera** [comment]
I think we should focus on a no-code user for this utility, and in fact maybe the point shouldn't be to provide the user with some files of a boilerplate theme but redirect them to the editor to start building on top of it right away
