### ISSUE TITLE
Add some kind of doc/explanation about the 'Theme subfolder' option.

### ISSUE THREAD

**Issue by matiasbenedetto** [WordPress/create-block-theme#716]
## What?

In the 'Edit theme metadata' modal, there's an option called  'Theme subfolder,' but it's not clear what it does or what to expect after changing it.

![image](https://github.com/user-attachments/assets/611ebd6d-ad19-4715-9cd0-53e7b48aa543)

## Expected

It should include at least some comment/doc explaining the behavior of this not obvious field.
Other fields in this modal have some explanations about their expected content. Example:
![image](https://github.com/user-attachments/assets/1353e3dc-ae10-4abe-9cc9-75f609165197)

**Comment by colorful-tones** [comment]
I was curious as to what the field is for and supposed to do. So, I put 'test' in the field, 'Saved' and now my WP install is "broken", because it took my `example` theme (currently activated) and nested it within `test`. My theme is now located at `wp-content/themes/test/example/..` whereas before it was `wp-content/themes/example/..`. I would be curious to know what and why this field exists. I agree that it is super confusing to have it with no explainer text. 🤔

**Comment by pbking** [comment]
I added this because most of the themes I was working on were in a subfolder in the themes folder (`/themes/pub` for example).  That was the folder of my git repository, etc.  Since the location I was managing themes in was non-standard I needed a way to move them in and out of that folder.

So when CBT clones a theme it clones it INTO the same folder the theme originates from.  (In my case `/themes/pub/blockbase` or whatever).  That field just allows a user to manage that stat themselves (outside of manipulating the filesystem).

**Comment by t-hamano** [comment]
We may also find the discussion in #500 useful regarding the purpose of this option.

**Comment by pbking** [comment]
It seems the easiest thing to do would be to remove the feature.  I don't feel strongly about it staying.

It mostly addressed a need in my personal environment that I could handle many other ways.

I opt for removing the feature and simplifying things.
