### ISSUE TITLE
after "Save Changes to Theme" links in footer are parsed to text

### ISSUE THREAD

**Issue by jaapwiering** [WordPress/create-block-theme#731]
First of all a loud "thank you" for this amazing plugin that makes creating (child) themes so much easier.

I encountered a bug when a saved changes in the footer to the child theme I created.

This was wat I created: some text with links:
<img width="258" alt="Scherm­afbeelding 2024-09-24 om 11 41 36" src="https://github.com/user-attachments/assets/7b88d879-9009-49cf-890a-a0fce1b8cf42">

And this was what appeared after I had saved the changes to the theme, when the theme was reloaded:
<img width="339" alt="Scherm­afbeelding 2024-09-24 om 11 39 14" src="https://github.com/user-attachments/assets/25ffa59a-0988-428a-b293-669ba95199a0">

To be precise: the links didn't work anymore. To me this is unexpected behavior and also unwanted.

**Comment by mikachan** [comment]
Thanks for reporting this, @jaapwiering! Glad to hear you're finding the plugin useful, too ✨ 

I believe this bug has already been reported in https://github.com/WordPress/create-block-theme/issues/691, and there is a fix that is almost ready to land in https://github.com/WordPress/create-block-theme/pull/719, so I'm going to close this issue as a duplicate. Thanks so much for reporting, and hopefully this issue will be fixed in the next release 🤞
