### ISSUE TITLE
Exported theme has minor line height difference in theme.json

### ISSUE THREAD

**Issue by erikjoling** [WordPress/create-block-theme#75]
Hi,

First of all, thanks for this plugin. I just installed it, but I already see the benefits for me as a theme developer.

I noticed a small issue: the line-height values in the exported theme's theme.json file were slightly off:

Original:
```
"line-height": {
	"tiny": 1.1,
	"small": 1.2,
	"medium": 1.4,
	"normal": 1.725
}
```

Export:
```
"line-height": {
	"medium": 1.3999999999999999,
	"normal": 1.7250000000000001,
	"small": 1.2,
	"tiny": 1.1000000000000001
}
```

Apparently they are also sorted different :stuck_out_tongue_winking_eye:

**Comment by pbking** [comment]
> Apparently they are also sorted different 😜

Ha.  The values are exported alphabetically, which I think is usually the right thing.  But that sure does make the sizes confusing!

Since this plugin gets the values from core/gutenberg it's likely caused by something there.  What type of export were you doing?  If you export directly from the FSE instead do you get the same result?

**Comment by erikjoling** [comment]
I'll try to check it out later this week

**Comment by mikachan** [comment]
I can no longer reproduce this, so I think this must have been fixed upstream in Gutenberg. Please re-open if you notice it happening again!
